# Generated by Django 6.0.2 on 2026-02-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/human_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
